language: python
python:
  - 3.7
  - 3.8
  - 3.9
sudo: required
dist: bionic

before_install:
  - eval "${MATRIX_EVAL}"

  # Compiler
  - $CC --version
  - $CXX --version

  # Google Test
  - git clone https://github.com/google/googletest.git
  - mkdir -p googletest/build && cd googletest/build
  - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
  - cmake --build . --parallel 4
  - sudo make install
  - cd -

  # Pip
  - pip install -U pip
  - pip install poetry

install:
  # C/C++
  - mkdir build && cd build
  - cmake .. -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON -DCMAKE_C_COMPILER=$CC -DCMAKE_CXX_COMPILER=$CXX
  - cmake --build . --parallel 4
  - cd -
  # Python
  - poetry install

script:
  # C/C++
  - make -C ./build check
  - poetry run nose2

branches:
  only:
    - master
    - dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-bionic-10
    packages:
      - gcc-9
      - g++-9
      - clang-10

env:
  matrix:
    - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

notifications:
  email:
    recipients: tatsy.mail@gmail.com
    on_success: change
    on_failure: always
